PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE sqlite_stat1(tbl,idx,stat);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_gacha_data",/*idx*/"event_gacha_data_0_event_id",/*stat*/"64 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_quiz",/*idx*/"hatsune_quiz_0_event_id_1_release_quest_id",/*stat*/"8 4 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_quiz",/*idx*/"hatsune_quiz_0_event_id",/*stat*/"8 4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"goldset_data_2",/*idx*/NULL,/*stat*/"70");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"serial_group_data",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"ttk_drama",/*idx*/"ttk_drama_0_drama_id",/*stat*/"62 11");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_unlock_story_condition",/*idx*/"hatsune_unlock_story_condition_0_event_id",/*stat*/"326 9");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_invite_level_group",/*idx*/NULL,/*stat*/"38");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"ssp_story_data",/*idx*/"ssp_story_data_0_contents_type",/*stat*/"22 6");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"ssp_story_data",/*idx*/"ssp_story_data_0_original_event_id",/*stat*/"22 22");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_special_battle",/*idx*/"hatsune_special_battle_0_wave_group_id",/*stat*/"141 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_special_battle",/*idx*/"hatsune_special_battle_0_event_id",/*stat*/"141 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_special_battle",/*idx*/"sqlite_autoindex_hatsune_special_battle_1",/*stat*/"141 3 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_introduction",/*idx*/"event_introduction_0_event_id",/*stat*/"59 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"stamp",/*idx*/NULL,/*stat*/"32");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"dungeon_area_data",/*idx*/NULL,/*stat*/"6");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_boss_enemy_setting",/*idx*/"hatsune_boss_enemy_setting_0_boss_id_1_event_id",/*stat*/"15 3 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_boss_enemy_setting",/*idx*/"sqlite_autoindex_hatsune_boss_enemy_setting_1",/*stat*/"15 3 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"fix_lineup_group_set",/*idx*/"fix_lineup_group_set_0_team_level_from_1_team_level_to",/*stat*/"24 3 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"fix_lineup_group_set",/*idx*/"sqlite_autoindex_fix_lineup_group_set_1",/*stat*/"24 4 1 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"sekai_top_data",/*idx*/"sekai_top_data_0_sekai_id",/*stat*/"22 11");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_release_data",/*idx*/NULL,/*stat*/"3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"fke_reward",/*idx*/NULL,/*stat*/"15");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"nyx_phase_data",/*idx*/NULL,/*stat*/"3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_boss_treasure_box",/*idx*/NULL,/*stat*/"242");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"shiori_event_list",/*idx*/NULL,/*stat*/"13");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"grand_arena_max_season_rank_reward",/*idx*/NULL,/*stat*/"118");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"birthday_login_bonus_data",/*idx*/NULL,/*stat*/"74");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"serial_code_data",/*idx*/NULL,/*stat*/"4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"pct_system_fruits",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"pct_system",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_quest_condition",/*idx*/"hatsune_quest_condition_0_event_id",/*stat*/"1320 20");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"login_bonus_adv",/*idx*/"login_bonus_adv_0_login_bonus_id",/*stat*/"32 5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"ske_story_script",/*idx*/"ske_story_script_0_story_id",/*stat*/"737 67");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_wave_group_data",/*idx*/NULL,/*stat*/"4518");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_quest_area",/*idx*/"hatsune_quest_area_0_event_id",/*stat*/"148 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"goldset_data_teamlevel",/*idx*/NULL,/*stat*/"200");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"nyx_story_script",/*idx*/"nyx_story_script_0_story_id",/*stat*/"785 72");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"dear_setting",/*idx*/NULL,/*stat*/"18");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"arena_max_rank_reward",/*idx*/NULL,/*stat*/"79");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"birthday_login_bonus_drama_script",/*idx*/"birthday_login_bonus_drama_script_0_drama_id",/*stat*/"491 62");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"growth_restriction_unit",/*idx*/"growth_restriction_unit_0_growth_id",/*stat*/"4 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"pct_combo_coefficient",/*idx*/NULL,/*stat*/"6");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"campaign_freegacha_data",/*idx*/NULL,/*stat*/"54");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"actual_unit_background",/*idx*/NULL,/*stat*/"146");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_effect_reward_get",/*idx*/"sqlite_autoindex_room_effect_reward_get_1",/*stat*/"87 8 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"voice_group",/*idx*/NULL,/*stat*/"108");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"seasonpass_mission_data",/*idx*/NULL,/*stat*/"67");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"seasonpass_foundation",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"fke_happening_list",/*idx*/NULL,/*stat*/"20");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tme_map_data",/*idx*/"tme_map_data_0_event_id",/*stat*/"12 12");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"uek_mission",/*idx*/NULL,/*stat*/"16");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"glossary_detail",/*idx*/NULL,/*stat*/"81");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"position_setting",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_period",/*idx*/"clan_battle_period_0_clan_battle_id",/*stat*/"37 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_period",/*idx*/"sqlite_autoindex_clan_battle_period_1",/*stat*/"37 1 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_chat_scenario",/*idx*/"room_chat_scenario_0_id",/*stat*/"277 10");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_chat_scenario",/*idx*/"sqlite_autoindex_room_chat_scenario_1",/*stat*/"277 10 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"login_bonus_detail",/*idx*/"login_bonus_detail_0_login_bonus_id_1_count",/*stat*/"235 10 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_status_coefficient",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"ttk_story",/*idx*/"ttk_story_0_ttk_score",/*stat*/"5 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"sekai_schedule",/*idx*/NULL,/*stat*/"2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"prizegacha_data",/*idx*/NULL,/*stat*/"34");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_last_attack_reward",/*idx*/NULL,/*stat*/"3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_schedule",/*idx*/NULL,/*stat*/"37");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"growth_parameter",/*idx*/NULL,/*stat*/"5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_background",/*idx*/NULL,/*stat*/"153");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"kaiser_special_battle",/*idx*/NULL,/*stat*/"3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"pkb_pitcher_ball_type",/*idx*/"pkb_pitcher_ball_type_0_pitcher_id",/*stat*/"17 5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"pkb_pitcher_ball_type",/*idx*/"sqlite_autoindex_pkb_pitcher_ball_type_1",/*stat*/"17 5 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_present",/*idx*/"hatsune_present_0_event_id",/*stat*/"6 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_cost_group",/*idx*/NULL,/*stat*/"6");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"navi_comment",/*idx*/NULL,/*stat*/"77");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"space_top_data",/*idx*/"space_top_data_0_story_id",/*stat*/"8 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"space_top_data",/*idx*/"space_top_data_0_space_id",/*stat*/"8 8");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_diary_data",/*idx*/"hatsune_diary_data_0_contents_type",/*stat*/"17 9");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"grand_arena_daily_rank_reward",/*idx*/NULL,/*stat*/"40");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_effect",/*idx*/NULL,/*stat*/"20");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_chat_info",/*idx*/NULL,/*stat*/"28");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_skill_data",/*idx*/NULL,/*stat*/"1048");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"pkb_batter_condition",/*idx*/NULL,/*stat*/"9");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"lto_letter_script",/*idx*/"lto_letter_script_0_letter_id",/*stat*/"54 54");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"album_production_list",/*idx*/"album_production_list_0_unit_id",/*stat*/"1356 9");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"still",/*idx*/"still_0_still_group_id",/*stat*/"935 5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"still",/*idx*/"still_0_story_id",/*stat*/"935 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"special_story_banner",/*idx*/"special_story_banner_0_story_group_id",/*stat*/"1 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"srt_reward",/*idx*/NULL,/*stat*/"15");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_reminder",/*idx*/"event_reminder_0_event_id",/*stat*/"7 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_revival_wave_group_data",/*idx*/NULL,/*stat*/"4518");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"shiori_stationary_mission_data",/*idx*/NULL,/*stat*/"299");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"campaign_freegacha_sp",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"story_quest_data",/*idx*/NULL,/*stat*/"14");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"seasonpass_mission_reward_data",/*idx*/"seasonpass_mission_reward_data_0_mission_reward_id",/*stat*/"18 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"shiori_boss_condition",/*idx*/NULL,/*stat*/"42");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"special_still",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"voice_group_chara",/*idx*/NULL,/*stat*/"75");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"dear_story_detail",/*idx*/"dear_story_detail_0_story_group_id",/*stat*/"438 26");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"dear_story_detail",/*idx*/"dear_story_detail_0_story_group_id_1_chara_index",/*stat*/"438 26 9");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"nyx_story_data",/*idx*/"nyx_story_data_0_story_phase",/*stat*/"15 5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"nyx_story_data",/*idx*/"nyx_story_data_0_story_seq",/*stat*/"15 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_s_boss_data",/*idx*/NULL,/*stat*/"190");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_2_map_data",/*idx*/"clan_battle_2_map_data_0_clan_battle_id",/*stat*/"154 5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"story_data",/*idx*/NULL,/*stat*/"200");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"spskill_label_data",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_diary_script",/*idx*/"hatsune_diary_script_0_diary_id",/*stat*/"427 31");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"gift_message",/*idx*/NULL,/*stat*/"109");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"skill_action",/*idx*/NULL,/*stat*/"5878");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"kaiser_extermination_reward",/*idx*/NULL,/*stat*/"4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"emblem_data",/*idx*/NULL,/*stat*/"639");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"vote_unit",/*idx*/"sqlite_autoindex_vote_unit_1",/*stat*/"55 55 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"pct_itempoint",/*idx*/"pct_itempoint_0_item_id",/*stat*/"3 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_diary_setting",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_quest",/*idx*/"hatsune_quest_0_event_id",/*stat*/"1280 20");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_unit_comments",/*idx*/"room_unit_comments_0_unit_id",/*stat*/"4591 24");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_unit_comments",/*idx*/"sqlite_autoindex_room_unit_comments_1",/*stat*/"4591 24 8 2 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tower_story_detail",/*idx*/NULL,/*stat*/"99");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"quest_annihilation",/*idx*/"sqlite_autoindex_quest_annihilation_1",/*stat*/"2 2 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"pkb_drama_data",/*idx*/NULL,/*stat*/"38");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"srt_score",/*idx*/NULL,/*stat*/"3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_daily_mission_data",/*idx*/NULL,/*stat*/"123");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"login_bonus_message_data",/*idx*/"login_bonus_message_data_0_login_bonus_id",/*stat*/"330 66");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"rarity_6_quest_data",/*idx*/"rarity_6_quest_data_0_rarity_6_quest_id",/*stat*/"27 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"shiori_enemy_parameter",/*idx*/NULL,/*stat*/"7328");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"goldset_data",/*idx*/NULL,/*stat*/"70");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"sekai_add_times_data",/*idx*/NULL,/*stat*/"12");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_s_map_data",/*idx*/"clan_battle_s_map_data_0_clan_battle_id",/*stat*/"134 4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_unique_equip",/*idx*/NULL,/*stat*/"107");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"story_detail",/*idx*/NULL,/*stat*/"1306");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"content_map_data",/*idx*/NULL,/*stat*/"5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"odds_name_data",/*idx*/NULL,/*stat*/"145");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_special_boss_ticket_count",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"sekai_boss_mode",/*idx*/NULL,/*stat*/"12");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"gacha_data",/*idx*/NULL,/*stat*/"415");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_character_skin_color",/*idx*/NULL,/*stat*/"150");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_item_detail",/*idx*/"room_item_detail_0_lvup_trigger_type_2_1_lvup_trigger_id_2",/*stat*/"540 540 540");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_item_detail",/*idx*/"room_item_detail_0_lvup_trigger_type_1_lvup_trigger_id",/*stat*/"540 270 270");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_item_detail",/*idx*/"sqlite_autoindex_room_item_detail_1",/*stat*/"540 2 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"quest_defeat_notice",/*idx*/NULL,/*stat*/"6");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"space_battle_data",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"space_schedule",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"pct_evaluation",/*idx*/NULL,/*stat*/"5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"uek_spine_anim_link",/*idx*/"uek_spine_anim_link_0_anim_num",/*stat*/"50 13");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_multi_route_parameter",/*idx*/"hatsune_multi_route_parameter_0_type",/*stat*/"20 5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_multi_route_parameter",/*idx*/"hatsune_multi_route_parameter_0_quest_id",/*stat*/"20 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_boss_condition",/*idx*/NULL,/*stat*/"274");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"sekai_enemy_parameter",/*idx*/NULL,/*stat*/"6");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_period_rank_reward",/*idx*/NULL,/*stat*/"555");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_story_detail",/*idx*/"event_story_detail_0_story_group_id",/*stat*/"322 9");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"worldmap",/*idx*/NULL,/*stat*/"4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"training_quest_data",/*idx*/NULL,/*stat*/"22");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_reminder_condition",/*idx*/"event_reminder_condition_0_reminder_id",/*stat*/"7 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_introduction",/*idx*/"unit_introduction_0_gacha_id",/*stat*/"119 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"quest_reward_data",/*idx*/NULL,/*stat*/"3052");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"quest_data",/*idx*/NULL,/*stat*/"801");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"emblem_mission_reward_data",/*idx*/"emblem_mission_reward_data_0_reward_id",/*stat*/"729 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"emblem_mission_reward_data",/*idx*/"emblem_mission_reward_data_0_mission_reward_id",/*stat*/"729 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tower_quest_fix_reward_group",/*idx*/NULL,/*stat*/"581");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_special_mission_data",/*idx*/NULL,/*stat*/"363");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"sekai_unlock_story_condition",/*idx*/NULL,/*stat*/"5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"dungeon_quest_data",/*idx*/NULL,/*stat*/"47");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"campaign_mission_reward_data",/*idx*/"campaign_mission_reward_data_0_campaign_mission_reward_id",/*stat*/"24 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"emblem_mission_data",/*idx*/NULL,/*stat*/"533");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"pct_gaming_motion",/*idx*/NULL,/*stat*/"8");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"dear_reward",/*idx*/"dear_reward_0_event_id_1_chara_index",/*stat*/"260 15 5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"shiori_mission_reward_data",/*idx*/"shiori_mission_reward_data_0_mission_reward_id",/*stat*/"637 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_unlock_unit_condition",/*idx*/"hatsune_unlock_unit_condition_0_condition_mission_id",/*stat*/"38 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_unlock_unit_condition",/*idx*/"hatsune_unlock_unit_condition_0_unit_id_1_event_id",/*stat*/"38 2 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_chat_formation",/*idx*/NULL,/*stat*/"6");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"campaign_mission_data",/*idx*/"campaign_mission_data_0_campaign_id_1_type",/*stat*/"28 14 7");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"campaign_mission_data",/*idx*/"campaign_mission_data_0_campaign_id",/*stat*/"28 14");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_relay_data",/*idx*/NULL,/*stat*/"48");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"custom_mypage_group",/*idx*/NULL,/*stat*/"5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"album_voice_list",/*idx*/"album_voice_list_0_unit_id",/*stat*/"3182 37");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"season_pack",/*idx*/"season_pack_0_mission_id",/*stat*/"27 5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tower_cloister_quest_data",/*idx*/NULL,/*stat*/"19");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_bg_change",/*idx*/NULL,/*stat*/"2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"custom_mypage",/*idx*/"custom_mypage_0_still_group_id",/*stat*/"95 95");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"guild",/*idx*/NULL,/*stat*/"18");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"mission_reward_data",/*idx*/"mission_reward_data_0_mission_reward_id",/*stat*/"622 4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"ttk_score",/*idx*/NULL,/*stat*/"4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tower_area_data",/*idx*/NULL,/*stat*/"31");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_boss_treasure_content",/*idx*/NULL,/*stat*/"1250");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"shiori_unlock_unit_condition",/*idx*/"shiori_unlock_unit_condition_0_condition_mission_id",/*stat*/"7 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"shiori_unlock_unit_condition",/*idx*/"shiori_unlock_unit_condition_0_unit_id_1_event_id",/*stat*/"7 1 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_quiz_condition",/*idx*/"hatsune_quiz_condition_0_event_id_1_quiz_id",/*stat*/"12 6 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_mission_reward_data",/*idx*/"hatsune_mission_reward_data_0_mission_reward_id",/*stat*/"4259 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"sd_navi_comment",/*idx*/NULL,/*stat*/"9");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"experience_team",/*idx*/NULL,/*stat*/"194");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"omp_drama",/*idx*/"omp_drama_0_drama_id",/*stat*/"601 67");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"arena_daily_rank_reward",/*idx*/NULL,/*stat*/"40");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_change",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"chara_fortune_rail",/*idx*/NULL,/*stat*/"86");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"story_character_mask",/*idx*/NULL,/*stat*/"524");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tips",/*idx*/NULL,/*stat*/"94");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"arcade_list",/*idx*/NULL,/*stat*/"6");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"kaiser_schedule",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"pkb_drama",/*idx*/"pkb_drama_0_drama_id",/*stat*/"429 12");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tower_quest_data",/*idx*/"tower_quest_data_0_floor_num",/*stat*/"520 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"minigame",/*idx*/"minigame_0_event_id",/*stat*/"6 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_series_wave_group_data",/*idx*/NULL,/*stat*/"4518");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_period_lap_reward",/*idx*/NULL,/*stat*/"256");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_2_boss_data",/*idx*/NULL,/*stat*/"190");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_skin_color",/*idx*/NULL,/*stat*/"3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"resist_data",/*idx*/NULL,/*stat*/"36");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"nyx_drama_script",/*idx*/"nyx_drama_script_0_drama_id",/*stat*/"735 74");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_special_enemy",/*idx*/NULL,/*stat*/"130");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_map",/*idx*/NULL,/*stat*/"14");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_item_announcement",/*idx*/NULL,/*stat*/"2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"enemy_m_parts",/*idx*/NULL,/*stat*/"136");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"ttk_story_script",/*idx*/"ttk_story_script_0_story_id",/*stat*/"227 46");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"chara_fortune_reward",/*idx*/NULL,/*stat*/"28");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"experience_unit",/*idx*/NULL,/*stat*/"194");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"vote_data",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_story_data",/*idx*/"event_story_data_0_value",/*stat*/"39 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"campaign_mission_schedule",/*idx*/NULL,/*stat*/"2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"equipment_craft",/*idx*/NULL,/*stat*/"314");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"shiori_wave_group_data",/*idx*/NULL,/*stat*/"840");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_stationary_mission_data",/*idx*/"hatsune_stationary_mission_data_0_event_id",/*stat*/"2025 32");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unlock_rarity_6",/*idx*/"unlock_rarity_6_0_material_id",/*stat*/"189 4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unlock_rarity_6",/*idx*/"unlock_rarity_6_0_unit_id_1_unlock_level",/*stat*/"189 7 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unlock_rarity_6",/*idx*/"unlock_rarity_6_0_unit_id_1_slot_id",/*stat*/"189 7 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unlock_rarity_6",/*idx*/"unlock_rarity_6_0_unit_id",/*stat*/"189 7");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unlock_rarity_6",/*idx*/"sqlite_autoindex_unlock_rarity_6_1",/*stat*/"189 7 3 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unique_equipment_craft",/*idx*/NULL,/*stat*/"111");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"item_e_ticket_data",/*idx*/"item_e_ticket_data_0_exchange_number",/*stat*/"27 7");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"item_e_ticket_data",/*idx*/"item_e_ticket_data_0_ticket_id",/*stat*/"27 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"item_e_ticket_data",/*idx*/"sqlite_autoindex_item_e_ticket_data_1",/*stat*/"27 3 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"pkb_reward",/*idx*/NULL,/*stat*/"14");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_odds_data",/*idx*/"clan_battle_odds_data_0_odds_group_id",/*stat*/"26 6");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_odds_data",/*idx*/"sqlite_autoindex_clan_battle_odds_data_1",/*stat*/"26 6 1 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_data",/*idx*/NULL,/*stat*/"191");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"ailment_data",/*idx*/NULL,/*stat*/"32");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"kmk_reward",/*idx*/NULL,/*stat*/"15");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"pct_tap_speed",/*idx*/NULL,/*stat*/"8");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"skip_monster_data",/*idx*/NULL,/*stat*/"2485");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"quest_condition_data",/*idx*/NULL,/*stat*/"804");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"enemy_enable_voice",/*idx*/NULL,/*stat*/"70");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clanprofile_content",/*idx*/NULL,/*stat*/"35");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"enemy_reward_data",/*idx*/NULL,/*stat*/"3093");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"dungeon_skip_data",/*idx*/NULL,/*stat*/"7");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_item",/*idx*/NULL,/*stat*/"456");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_training_data",/*idx*/"clan_battle_training_data_0_training_id",/*stat*/"5 5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"skill_cost",/*idx*/NULL,/*stat*/"196");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"notif_data",/*idx*/"notif_data_0_unit_id",/*stat*/"900 6");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"notif_data",/*idx*/"sqlite_autoindex_notif_data_1",/*stat*/"900 6 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"arcade_story_list",/*idx*/"arcade_story_list_0_arcade_id",/*stat*/"14 5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"omp_story_data",/*idx*/"omp_story_data_0_story_seq",/*stat*/"15 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"omp_story_data",/*idx*/"omp_story_data_0_event_id",/*stat*/"15 8");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"uek_boss",/*idx*/"uek_boss_0_enemy_id",/*stat*/"4 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unlock_skill_data",/*idx*/NULL,/*stat*/"4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"myprofile_content",/*idx*/NULL,/*stat*/"24");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"kaiser_quest_data",/*idx*/NULL,/*stat*/"5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"vote_info",/*idx*/"sqlite_autoindex_vote_info_1",/*stat*/"3 3 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tower_schedule",/*idx*/"tower_schedule_0_opening_story_id",/*stat*/"31 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_enemy_reward_group",/*idx*/NULL,/*stat*/"137");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_diary_letter_script",/*idx*/"hatsune_diary_letter_script_0_diary_id",/*stat*/"151 51");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_description",/*idx*/"hatsune_description_0_event_id_1_type",/*stat*/"384 6 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"campaign_freegacha",/*idx*/NULL,/*stat*/"16");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_recommend_data",/*idx*/"clan_battle_recommend_data_0_recommend_group",/*stat*/"9 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"arena_max_season_rank_reward",/*idx*/NULL,/*stat*/"118");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_promotion_status",/*idx*/"sqlite_autoindex_unit_promotion_status_1",/*stat*/"3040 19 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_comments",/*idx*/"unit_comments_0_unit_id_1_use_type",/*stat*/"1963 6 4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_comments",/*idx*/"unit_comments_0_unit_id",/*stat*/"1963 6");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"dear_story_data",/*idx*/"dear_story_data_0_value",/*stat*/"17 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"quest_area_data",/*idx*/NULL,/*stat*/"103");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unique_equipment_data",/*idx*/NULL,/*stat*/"111");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"music_list",/*idx*/NULL,/*stat*/"167");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_top_adv",/*idx*/"event_top_adv_0_event_id_1_type",/*stat*/"752 12 4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"shiori_boss",/*idx*/"shiori_boss_0_wave_group_id_1",/*stat*/"39 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"shiori_boss",/*idx*/"shiori_boss_0_event_id_1_difficulty",/*stat*/"39 3 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"shiori_boss",/*idx*/"shiori_boss_0_event_id",/*stat*/"39 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_bg_change_data",/*idx*/"hatsune_bg_change_data_0_target_type_1_area_id",/*stat*/"21 11 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"gacha_exchange_lineup",/*idx*/"gacha_exchange_lineup_0_exchange_id",/*stat*/"214 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"campaign_schedule",/*idx*/NULL,/*stat*/"763");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_rarity",/*idx*/"unit_rarity_0_unit_material_id",/*stat*/"887 6");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_rarity",/*idx*/"unit_rarity_0_unit_id",/*stat*/"887 6");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_rarity",/*idx*/"sqlite_autoindex_unit_rarity_1",/*stat*/"887 6 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"enemy_parameter",/*idx*/NULL,/*stat*/"8813");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tower_enemy_parameter",/*idx*/NULL,/*stat*/"3039");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"ticket_gacha_data",/*idx*/NULL,/*stat*/"5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"content_release_data",/*idx*/NULL,/*stat*/"36");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"sekai_boss_damage_rank_reward",/*idx*/NULL,/*stat*/"15");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"grand_arena_max_rank_reward",/*idx*/NULL,/*stat*/"79");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"combined_result_motion",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_profile",/*idx*/NULL,/*stat*/"157");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"specialfes_banner",/*idx*/NULL,/*stat*/"11");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"ttk_weapon",/*idx*/"ttk_weapon_0_ttk_score",/*stat*/"4 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tower_wave_group_data",/*idx*/NULL,/*stat*/"619");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"login_bonus_data",/*idx*/NULL,/*stat*/"27");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_attack_pattern",/*idx*/NULL,/*stat*/"1259");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"chara_story_status",/*idx*/NULL,/*stat*/"820");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"visual_customize",/*idx*/NULL,/*stat*/"13");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"music_content",/*idx*/NULL,/*stat*/"170");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tower_ex_quest_data",/*idx*/"tower_ex_quest_data_0_floor_num",/*stat*/"31 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_enemy_parameter",/*idx*/NULL,/*stat*/"3764");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"shiori_description",/*idx*/"shiori_description_0_type",/*stat*/"9 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"shiori_quest_area",/*idx*/"shiori_quest_area_0_event_id",/*stat*/"30 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_emotion_icon",/*idx*/NULL,/*stat*/"18");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"spskill_lv_initialize_data",/*idx*/NULL,/*stat*/"3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"return_specialfes_banner",/*idx*/NULL,/*stat*/"8");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_emblem_mission",/*idx*/"hatsune_emblem_mission_0_event_id",/*stat*/"117 5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"sekai_top_story_data",/*idx*/"sekai_top_story_data_0_sekai_id",/*stat*/"4 4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_grade",/*idx*/NULL,/*stat*/"10");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_item_get_announcement",/*idx*/NULL,/*stat*/"6");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"bg_data",/*idx*/"sqlite_autoindex_bg_data_1",/*stat*/"147 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"ttk_enemy",/*idx*/NULL,/*stat*/"8");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"chara_fortune_scenario",/*idx*/NULL,/*stat*/"52");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"skill_data",/*idx*/NULL,/*stat*/"2488");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"love_chara",/*idx*/NULL,/*stat*/"12");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_boss",/*idx*/"hatsune_boss_0_wave_group_id_1",/*stat*/"274 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_boss",/*idx*/"hatsune_boss_0_event_id_1_difficulty",/*stat*/"274 5 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_boss",/*idx*/"hatsune_boss_0_event_id",/*stat*/"274 5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_boss_damage_rank",/*idx*/"clan_battle_boss_damage_rank_0_damage_rank_id",/*stat*/"160 4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_boss_damage_rank",/*idx*/"sqlite_autoindex_clan_battle_boss_damage_rank_1",/*stat*/"160 4 1 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"wave_group_data",/*idx*/NULL,/*stat*/"3986");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"campaign_mission_category",/*idx*/"campaign_mission_category_0_campaign_id_1_type",/*stat*/"4 2 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"equipment_enhance_rate",/*idx*/NULL,/*stat*/"351");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"kaiser_restriction_group",/*idx*/"kaiser_restriction_group_0_restriction_group_id",/*stat*/"102 21");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"kaiser_restriction_group",/*idx*/"sqlite_autoindex_kaiser_restriction_group_1",/*stat*/"102 21 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"srt_top_talk",/*idx*/"srt_top_talk_0_talk_id",/*stat*/"45 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"srt_panel",/*idx*/"srt_panel_0_version",/*stat*/"438 438");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"srt_panel",/*idx*/"srt_panel_0_panel_id",/*stat*/"438 4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"nyx_drama_data",/*idx*/NULL,/*stat*/"10");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"skip_boss_data",/*idx*/NULL,/*stat*/"112");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"global_data",/*idx*/"sqlite_autoindex_global_data_1",/*stat*/"2 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"ttk_navi_comment",/*idx*/NULL,/*stat*/"13");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_quiz_reward",/*idx*/NULL,/*stat*/"8");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tower_story_data",/*idx*/NULL,/*stat*/"17");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"equipment_enhance_data",/*idx*/"sqlite_autoindex_equipment_enhance_data_1",/*stat*/"19 4 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"pct_result",/*idx*/"pct_result_0_character_id",/*stat*/"4 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"shop_static_price_group",/*idx*/NULL,/*stat*/"6");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_bg_data",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"birthday_login_bonus_detail",/*idx*/"birthday_login_bonus_detail_0_login_bonus_id",/*stat*/"78 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"profile_frame",/*idx*/NULL,/*stat*/"11");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"seasonpass_level_reward",/*idx*/NULL,/*stat*/"100");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_effect_setting",/*idx*/"sqlite_autoindex_event_effect_setting_1",/*stat*/"48 3 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"grand_arena_defence_reward",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"chara_fortune_schedule",/*idx*/NULL,/*stat*/"7");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_mypage_pos",/*idx*/NULL,/*stat*/"36");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unlock_unit_condition",/*idx*/NULL,/*stat*/"150");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"daily_mission_data",/*idx*/NULL,/*stat*/"398");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"equipment_donation",/*idx*/NULL,/*stat*/"9");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"equipment_data",/*idx*/NULL,/*stat*/"665");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_map_event",/*idx*/"hatsune_map_event_0_target_event_id",/*stat*/"121 9");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"movie",/*idx*/"movie_0_story_id",/*stat*/"299 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"chara_identity",/*idx*/NULL,/*stat*/"153");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"define_spskill",/*idx*/"define_spskill_0_sp_skill_id",/*stat*/"3 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"character_love_rankup_text",/*idx*/NULL,/*stat*/"42");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"srt_action",/*idx*/"sqlite_autoindex_srt_action_1",/*stat*/"41 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"shiori_item",/*idx*/NULL,/*stat*/"13");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"arena_defence_reward",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"banner",/*idx*/NULL,/*stat*/"151");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"stationary_mission_data",/*idx*/NULL,/*stat*/"1228");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"lto_story_data",/*idx*/"lto_story_data_0_event_id",/*stat*/"1 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"dear_chara",/*idx*/"dear_chara_0_event_id",/*stat*/"50 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"dear_chara",/*idx*/"sqlite_autoindex_dear_chara_1",/*stat*/"50 3 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_enemy_data",/*idx*/NULL,/*stat*/"926");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unique_equipment_enhance_data",/*idx*/"sqlite_autoindex_unique_equipment_enhance_data_1",/*stat*/"199 199 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"kmk_navi_comment",/*idx*/NULL,/*stat*/"11");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"ske_story_data",/*idx*/"ske_story_data_0_original_event_id",/*stat*/"12 6");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unique_equipment_enhance_rate",/*idx*/NULL,/*stat*/"111");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_item",/*idx*/NULL,/*stat*/"66");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_motion_list",/*idx*/NULL,/*stat*/"152");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"dodge_tp_recovery",/*idx*/NULL,/*stat*/"39");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unique_equipment_rankup",/*idx*/"unique_equipment_rankup_0_equip_id",/*stat*/"1332 12");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unique_equipment_rankup",/*idx*/"sqlite_autoindex_unique_equipment_rankup_1",/*stat*/"1332 12 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_emblem_mission_reward",/*idx*/"hatsune_emblem_mission_reward_0_reward_id",/*stat*/"231 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_emblem_mission_reward",/*idx*/"hatsune_emblem_mission_reward_0_mission_reward_id",/*stat*/"231 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"pkb_navi_comment",/*idx*/NULL,/*stat*/"33");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_schedule",/*idx*/"hatsune_schedule_0_original_event_id",/*stat*/"64 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_schedule",/*idx*/"hatsune_schedule_0_series_event_id",/*stat*/"64 16");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_character_personality",/*idx*/NULL,/*stat*/"155");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"guild_additional_member",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_promotion",/*idx*/"unit_promotion_0_unit_id",/*stat*/"3520 20");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_promotion",/*idx*/"sqlite_autoindex_unit_promotion_1",/*stat*/"3520 20 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"item_data",/*idx*/NULL,/*stat*/"347");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"ttk_reward",/*idx*/"ttk_reward_0_ttk_score",/*stat*/"2 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_navi_comment_condition",/*idx*/NULL,/*stat*/"253");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"shiori_quest_condition",/*idx*/NULL,/*stat*/"260");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_s_boss_fix_reward",/*idx*/NULL,/*stat*/"350");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"reward_collect_guide",/*idx*/NULL,/*stat*/"426");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"kaiser_add_times_data",/*idx*/NULL,/*stat*/"192");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"pct_reward",/*idx*/"pct_reward_0_pct_point_type",/*stat*/"15 5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"uek_drama",/*idx*/"uek_drama_0_drama_id",/*stat*/"379 10");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"shiori_quest",/*idx*/"shiori_quest_0_drop_reward_id",/*stat*/"260 10");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"shiori_quest",/*idx*/"shiori_quest_0_event_id",/*stat*/"260 20");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"sekai_boss_fix_reward",/*idx*/NULL,/*stat*/"10");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_boss_fix_reward",/*idx*/NULL,/*stat*/"40");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_setup",/*idx*/NULL,/*stat*/"383");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_navi_comment",/*idx*/NULL,/*stat*/"1133");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"cooperation_quest_data",/*idx*/NULL,/*stat*/"6");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"chara_e_ticket_data",/*idx*/"chara_e_ticket_data_0_jewel_store_id",/*stat*/"2 1");
COMMIT;