PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE sqlite_stat1(tbl,idx,stat);
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_gacha_data",/*idx*/NULL,/*stat*/"33");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_quiz",/*idx*/"hatsune_quiz_0_event_id",/*stat*/"4 4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"goldset_data_2",/*idx*/NULL,/*stat*/"70");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_wave_group_data",/*idx*/NULL,/*stat*/"4518");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_quest_area",/*idx*/"hatsune_quest_area_0_event_id",/*stat*/"76 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"goldset_data_teamlevel",/*idx*/NULL,/*stat*/"200");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_unlock_story_condition",/*idx*/NULL,/*stat*/"188");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_invite_level_group",/*idx*/NULL,/*stat*/"31");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_special_battle",/*idx*/"hatsune_special_battle_0_event_id",/*stat*/"45 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_special_battle",/*idx*/"sqlite_autoindex_hatsune_special_battle_1",/*stat*/"45 3 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_introduction",/*idx*/NULL,/*stat*/"34");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"stamp",/*idx*/NULL,/*stat*/"32");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"dungeon_area_data",/*idx*/NULL,/*stat*/"5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"fke_reward",/*idx*/NULL,/*stat*/"15");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_boss_treasure_box",/*idx*/NULL,/*stat*/"114");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"grand_arena_max_season_rank_reward",/*idx*/NULL,/*stat*/"118");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"dear_setting",/*idx*/NULL,/*stat*/"7");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"arena_max_rank_reward",/*idx*/NULL,/*stat*/"79");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"album_production_list",/*idx*/"album_production_list_0_unit_id",/*stat*/"904 9");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"still",/*idx*/"still_0_story_id",/*stat*/"621 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"fix_lineup_group_set",/*idx*/"fix_lineup_group_set_0_team_level_from_1_team_level_to",/*stat*/"22 3 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"fix_lineup_group_set",/*idx*/"sqlite_autoindex_fix_lineup_group_set_1",/*stat*/"22 4 1 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"sekai_top_data",/*idx*/NULL,/*stat*/"10");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_release_data",/*idx*/NULL,/*stat*/"3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"pct_system_fruits",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"pct_system",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_quest_condition",/*idx*/NULL,/*stat*/"680");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"login_bonus_adv",/*idx*/"login_bonus_adv_0_login_bonus_id",/*stat*/"10 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"pct_combo_coefficient",/*idx*/NULL,/*stat*/"6");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"campaign_freegacha_data",/*idx*/NULL,/*stat*/"24");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"actual_unit_background",/*idx*/NULL,/*stat*/"102");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_effect_reward_get",/*idx*/"sqlite_autoindex_room_effect_reward_get_1",/*stat*/"69 8 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"voice_group",/*idx*/NULL,/*stat*/"93");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"seasonpass_mission_data",/*idx*/NULL,/*stat*/"64");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"seasonpass_foundation",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"fke_happening_list",/*idx*/NULL,/*stat*/"20");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"glossary_detail",/*idx*/NULL,/*stat*/"81");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"position_setting",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_period",/*idx*/"clan_battle_period_0_clan_battle_id",/*stat*/"23 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_period",/*idx*/"sqlite_autoindex_clan_battle_period_1",/*stat*/"23 1 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_chat_scenario",/*idx*/"room_chat_scenario_0_id",/*stat*/"274 11");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_chat_scenario",/*idx*/"sqlite_autoindex_room_chat_scenario_1",/*stat*/"274 11 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"login_bonus_detail",/*idx*/"login_bonus_detail_0_login_bonus_id_1_count",/*stat*/"152 9 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_status_coefficient",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"sekai_schedule",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"prizegacha_data",/*idx*/NULL,/*stat*/"8");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_last_attack_reward",/*idx*/NULL,/*stat*/"3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_schedule",/*idx*/NULL,/*stat*/"23");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_background",/*idx*/NULL,/*stat*/"113");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"kaiser_special_battle",/*idx*/NULL,/*stat*/"3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_present",/*idx*/"hatsune_present_0_event_id",/*stat*/"4 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_cost_group",/*idx*/NULL,/*stat*/"6");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"navi_comment",/*idx*/NULL,/*stat*/"75");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_diary_data",/*idx*/"hatsune_diary_data_0_contents_type",/*stat*/"17 9");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"grand_arena_daily_rank_reward",/*idx*/NULL,/*stat*/"40");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_effect",/*idx*/NULL,/*stat*/"12");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_chat_info",/*idx*/NULL,/*stat*/"25");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_skill_data",/*idx*/NULL,/*stat*/"691");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"srt_reward",/*idx*/NULL,/*stat*/"15");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_revival_wave_group_data",/*idx*/NULL,/*stat*/"4518");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"story_quest_data",/*idx*/NULL,/*stat*/"14");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"seasonpass_mission_reward_data",/*idx*/"seasonpass_mission_reward_data_0_mission_reward_id",/*stat*/"18 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"voice_group_chara",/*idx*/NULL,/*stat*/"65");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"dear_story_detail",/*idx*/"dear_story_detail_0_story_group_id_1_chara_index",/*stat*/"172 25 10");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_s_boss_data",/*idx*/NULL,/*stat*/"120");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_2_map_data",/*idx*/"clan_battle_2_map_data_0_clan_battle_id",/*stat*/"79 4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"story_data",/*idx*/NULL,/*stat*/"149");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_diary_script",/*idx*/"hatsune_diary_script_0_diary_id",/*stat*/"427 31");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"gift_message",/*idx*/NULL,/*stat*/"84");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"skill_action",/*idx*/NULL,/*stat*/"3507");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"kaiser_extermination_reward",/*idx*/NULL,/*stat*/"4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"emblem_data",/*idx*/NULL,/*stat*/"410");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"vote_unit",/*idx*/"sqlite_autoindex_vote_unit_1",/*stat*/"55 55 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"pct_itempoint",/*idx*/"pct_itempoint_0_item_id",/*stat*/"3 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_diary_setting",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_quest",/*idx*/"hatsune_quest_0_event_id",/*stat*/"660 20");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_unit_comments",/*idx*/"room_unit_comments_0_unit_id",/*stat*/"3547 24");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_unit_comments",/*idx*/"sqlite_autoindex_room_unit_comments_1",/*stat*/"3547 24 8 2 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tower_story_detail",/*idx*/NULL,/*stat*/"60");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"srt_score",/*idx*/NULL,/*stat*/"3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_daily_mission_data",/*idx*/NULL,/*stat*/"67");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"login_bonus_message_data",/*idx*/"login_bonus_message_data_0_login_bonus_id",/*stat*/"118 40");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"rarity_6_quest_data",/*idx*/"rarity_6_quest_data_0_rarity_6_quest_id",/*stat*/"8 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"goldset_data",/*idx*/NULL,/*stat*/"70");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"sekai_add_times_data",/*idx*/NULL,/*stat*/"12");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_s_map_data",/*idx*/"clan_battle_s_map_data_0_clan_battle_id",/*stat*/"78 4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_unique_equip",/*idx*/NULL,/*stat*/"73");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"story_detail",/*idx*/NULL,/*stat*/"948");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"content_map_data",/*idx*/NULL,/*stat*/"4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"odds_name_data",/*idx*/NULL,/*stat*/"81");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_special_boss_ticket_count",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"sekai_boss_mode",/*idx*/NULL,/*stat*/"6");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"gacha_data",/*idx*/NULL,/*stat*/"226");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_character_skin_color",/*idx*/NULL,/*stat*/"106");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_item_detail",/*idx*/"room_item_detail_0_lvup_trigger_type_2_1_lvup_trigger_id_2",/*stat*/"487 487 487");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_item_detail",/*idx*/"room_item_detail_0_lvup_trigger_type_1_lvup_trigger_id",/*stat*/"487 244 244");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_item_detail",/*idx*/"sqlite_autoindex_room_item_detail_1",/*stat*/"487 2 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"quest_defeat_notice",/*idx*/NULL,/*stat*/"6");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"pct_evaluation",/*idx*/NULL,/*stat*/"5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_multi_route_parameter",/*idx*/"hatsune_multi_route_parameter_0_type",/*stat*/"10 4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_multi_route_parameter",/*idx*/"hatsune_multi_route_parameter_0_quest_id",/*stat*/"10 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_boss_condition",/*idx*/NULL,/*stat*/"119");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"sekai_enemy_parameter",/*idx*/NULL,/*stat*/"3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_period_rank_reward",/*idx*/NULL,/*stat*/"345");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_story_detail",/*idx*/"event_story_detail_0_story_group_id",/*stat*/"188 9");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"worldmap",/*idx*/NULL,/*stat*/"4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"training_quest_data",/*idx*/NULL,/*stat*/"16");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_introduction",/*idx*/"unit_introduction_0_gacha_id",/*stat*/"62 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"quest_reward_data",/*idx*/NULL,/*stat*/"1499");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"quest_data",/*idx*/NULL,/*stat*/"560");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"emblem_mission_reward_data",/*idx*/"emblem_mission_reward_data_0_reward_id",/*stat*/"498 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"emblem_mission_reward_data",/*idx*/"emblem_mission_reward_data_0_mission_reward_id",/*stat*/"498 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tower_quest_fix_reward_group",/*idx*/NULL,/*stat*/"413");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_special_mission_data",/*idx*/NULL,/*stat*/"107");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"sekai_unlock_story_condition",/*idx*/NULL,/*stat*/"5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"dungeon_quest_data",/*idx*/NULL,/*stat*/"37");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"campaign_mission_reward_data",/*idx*/"campaign_mission_reward_data_0_campaign_mission_reward_id",/*stat*/"12 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"emblem_mission_data",/*idx*/NULL,/*stat*/"376");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"pct_gaming_motion",/*idx*/NULL,/*stat*/"8");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"dear_reward",/*idx*/"dear_reward_0_event_id_1_chara_index",/*stat*/"90 13 5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_unlock_unit_condition",/*idx*/NULL,/*stat*/"20");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_chat_formation",/*idx*/NULL,/*stat*/"5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"campaign_mission_data",/*idx*/"campaign_mission_data_0_campaign_id_1_type",/*stat*/"16 16 8");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"campaign_mission_data",/*idx*/"campaign_mission_data_0_campaign_id",/*stat*/"16 16");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_relay_data",/*idx*/NULL,/*stat*/"48");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"album_voice_list",/*idx*/"album_voice_list_0_unit_id",/*stat*/"3182 37");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"season_pack",/*idx*/"season_pack_0_mission_id",/*stat*/"11 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tower_area_data",/*idx*/NULL,/*stat*/"18");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_boss_treasure_content",/*idx*/NULL,/*stat*/"546");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_quiz_condition",/*idx*/"hatsune_quiz_condition_0_event_id_1_quiz_id",/*stat*/"6 6 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_mission_reward_data",/*idx*/"hatsune_mission_reward_data_0_mission_reward_id",/*stat*/"2046 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"sd_navi_comment",/*idx*/NULL,/*stat*/"7");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"experience_team",/*idx*/NULL,/*stat*/"155");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"arena_daily_rank_reward",/*idx*/NULL,/*stat*/"40");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_change",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"story_character_mask",/*idx*/NULL,/*stat*/"352");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tips",/*idx*/NULL,/*stat*/"72");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"arcade_list",/*idx*/NULL,/*stat*/"4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"kaiser_schedule",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tower_quest_data",/*idx*/"tower_quest_data_0_floor_num",/*stat*/"390 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"minigame",/*idx*/"minigame_0_event_id",/*stat*/"4 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_period_lap_reward",/*idx*/NULL,/*stat*/"186");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_2_boss_data",/*idx*/NULL,/*stat*/"120");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_skin_color",/*idx*/NULL,/*stat*/"3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"resist_data",/*idx*/NULL,/*stat*/"32");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_special_enemy",/*idx*/NULL,/*stat*/"39");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_map",/*idx*/NULL,/*stat*/"14");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_item_announcement",/*idx*/NULL,/*stat*/"2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"enemy_m_parts",/*idx*/NULL,/*stat*/"28");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"chara_fortune_reward",/*idx*/NULL,/*stat*/"20");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"experience_unit",/*idx*/NULL,/*stat*/"155");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"vote_data",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_story_data",/*idx*/"event_story_data_0_value",/*stat*/"23 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"campaign_mission_schedule",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"equipment_craft",/*idx*/NULL,/*stat*/"236");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_stationary_mission_data",/*idx*/NULL,/*stat*/"1043");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unlock_rarity_6",/*idx*/"unlock_rarity_6_0_material_id",/*stat*/"56 4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unlock_rarity_6",/*idx*/"unlock_rarity_6_0_unit_id_1_unlock_level",/*stat*/"56 7 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unlock_rarity_6",/*idx*/"unlock_rarity_6_0_unit_id_1_slot_id",/*stat*/"56 7 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unlock_rarity_6",/*idx*/"sqlite_autoindex_unlock_rarity_6_1",/*stat*/"56 7 3 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unique_equipment_craft",/*idx*/NULL,/*stat*/"74");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_odds_data",/*idx*/"clan_battle_odds_data_0_odds_group_id",/*stat*/"22 5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_odds_data",/*idx*/"sqlite_autoindex_clan_battle_odds_data_1",/*stat*/"22 5 1 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_data",/*idx*/NULL,/*stat*/"147");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"ailment_data",/*idx*/NULL,/*stat*/"29");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"kmk_reward",/*idx*/NULL,/*stat*/"15");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"pct_tap_speed",/*idx*/NULL,/*stat*/"8");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"skip_monster_data",/*idx*/NULL,/*stat*/"1264");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"quest_condition_data",/*idx*/NULL,/*stat*/"561");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"enemy_enable_voice",/*idx*/NULL,/*stat*/"45");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clanprofile_content",/*idx*/NULL,/*stat*/"29");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"enemy_reward_data",/*idx*/NULL,/*stat*/"2042");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_item",/*idx*/NULL,/*stat*/"423");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"skill_cost",/*idx*/NULL,/*stat*/"157");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"notif_data",/*idx*/"notif_data_0_unit_id",/*stat*/"636 6");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"notif_data",/*idx*/"sqlite_autoindex_notif_data_1",/*stat*/"636 6 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"arcade_story_list",/*idx*/NULL,/*stat*/"8");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unlock_skill_data",/*idx*/NULL,/*stat*/"4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"myprofile_content",/*idx*/NULL,/*stat*/"19");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"kaiser_quest_data",/*idx*/NULL,/*stat*/"5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"vote_info",/*idx*/"sqlite_autoindex_vote_info_1",/*stat*/"3 3 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tower_schedule",/*idx*/"tower_schedule_0_opening_story_id",/*stat*/"18 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_enemy_reward_group",/*idx*/NULL,/*stat*/"137");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_diary_letter_script",/*idx*/"hatsune_diary_letter_script_0_diary_id",/*stat*/"151 51");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_description",/*idx*/"hatsune_description_0_event_id_1_type",/*stat*/"179 6 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"campaign_freegacha",/*idx*/NULL,/*stat*/"8");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"arena_max_season_rank_reward",/*idx*/NULL,/*stat*/"118");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_promotion_status",/*idx*/"sqlite_autoindex_unit_promotion_status_1",/*stat*/"1740 15 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_comments",/*idx*/"unit_comments_0_unit_id_1_use_type",/*stat*/"1336 6 4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_comments",/*idx*/"unit_comments_0_unit_id",/*stat*/"1336 6");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"dear_story_data",/*idx*/"dear_story_data_0_value",/*stat*/"7 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"quest_area_data",/*idx*/NULL,/*stat*/"71");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unique_equipment_data",/*idx*/NULL,/*stat*/"74");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"music_list",/*idx*/NULL,/*stat*/"114");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_top_adv",/*idx*/"event_top_adv_0_event_id_1_type",/*stat*/"289 11 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_bg_change_data",/*idx*/"hatsune_bg_change_data_0_target_type_1_area_id",/*stat*/"10 5 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"gacha_exchange_lineup",/*idx*/NULL,/*stat*/"104");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"campaign_schedule",/*idx*/NULL,/*stat*/"381");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_rarity",/*idx*/"unit_rarity_0_unit_material_id",/*stat*/"648 6");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_rarity",/*idx*/"unit_rarity_0_unit_id",/*stat*/"648 6");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_rarity",/*idx*/"sqlite_autoindex_unit_rarity_1",/*stat*/"648 6 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"enemy_parameter",/*idx*/NULL,/*stat*/"5180");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tower_enemy_parameter",/*idx*/NULL,/*stat*/"2073");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"content_release_data",/*idx*/NULL,/*stat*/"29");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"sekai_boss_damage_rank_reward",/*idx*/NULL,/*stat*/"12");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"grand_arena_max_rank_reward",/*idx*/NULL,/*stat*/"79");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"combined_result_motion",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_profile",/*idx*/NULL,/*stat*/"114");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"specialfes_banner",/*idx*/NULL,/*stat*/"4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tower_wave_group_data",/*idx*/NULL,/*stat*/"423");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"login_bonus_data",/*idx*/NULL,/*stat*/"18");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_attack_pattern",/*idx*/NULL,/*stat*/"852");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"chara_story_status",/*idx*/NULL,/*stat*/"592");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"visual_customize",/*idx*/NULL,/*stat*/"3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"music_content",/*idx*/NULL,/*stat*/"117");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tower_ex_quest_data",/*idx*/"tower_ex_quest_data_0_floor_num",/*stat*/"18 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_enemy_parameter",/*idx*/NULL,/*stat*/"3764");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_emotion_icon",/*idx*/NULL,/*stat*/"18");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_emblem_mission",/*idx*/NULL,/*stat*/"45");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"sekai_top_story_data",/*idx*/NULL,/*stat*/"4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_grade",/*idx*/NULL,/*stat*/"10");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"bg_data",/*idx*/"sqlite_autoindex_bg_data_1",/*stat*/"118 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"skill_data",/*idx*/NULL,/*stat*/"1571");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"love_chara",/*idx*/NULL,/*stat*/"12");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_boss",/*idx*/"hatsune_boss_0_event_id_1_difficulty",/*stat*/"119 4 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_boss_damage_rank",/*idx*/"clan_battle_boss_damage_rank_0_damage_rank_id",/*stat*/"160 4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_boss_damage_rank",/*idx*/"sqlite_autoindex_clan_battle_boss_damage_rank_1",/*stat*/"160 4 1 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"wave_group_data",/*idx*/NULL,/*stat*/"2387");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"campaign_mission_category",/*idx*/"campaign_mission_category_0_campaign_id_1_type",/*stat*/"2 2 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"equipment_enhance_rate",/*idx*/NULL,/*stat*/"273");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"kaiser_restriction_group",/*idx*/"kaiser_restriction_group_0_restriction_group_id",/*stat*/"102 21");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"kaiser_restriction_group",/*idx*/"sqlite_autoindex_kaiser_restriction_group_1",/*stat*/"102 21 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"srt_top_talk",/*idx*/"srt_top_talk_0_talk_id",/*stat*/"45 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"srt_panel",/*idx*/"srt_panel_0_panel_id",/*stat*/"438 4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"skip_boss_data",/*idx*/NULL,/*stat*/"68");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"global_data",/*idx*/"sqlite_autoindex_global_data_1",/*stat*/"2 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_quiz_reward",/*idx*/NULL,/*stat*/"4");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tower_story_data",/*idx*/NULL,/*stat*/"10");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"equipment_enhance_data",/*idx*/"sqlite_autoindex_equipment_enhance_data_1",/*stat*/"14 4 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"pct_result",/*idx*/"pct_result_0_character_id",/*stat*/"4 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"shop_static_price_group",/*idx*/NULL,/*stat*/"6");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_bg_data",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"profile_frame",/*idx*/NULL,/*stat*/"11");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"seasonpass_level_reward",/*idx*/NULL,/*stat*/"100");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"grand_arena_defence_reward",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"chara_fortune_schedule",/*idx*/NULL,/*stat*/"5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_mypage_pos",/*idx*/NULL,/*stat*/"36");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unlock_unit_condition",/*idx*/NULL,/*stat*/"107");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"daily_mission_data",/*idx*/NULL,/*stat*/"374");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"equipment_donation",/*idx*/NULL,/*stat*/"9");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"equipment_data",/*idx*/NULL,/*stat*/"509");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_map_event",/*idx*/"hatsune_map_event_0_target_event_id",/*stat*/"91 11");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"movie",/*idx*/NULL,/*stat*/"184");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"chara_identity",/*idx*/NULL,/*stat*/"110");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"character_love_rankup_text",/*idx*/NULL,/*stat*/"42");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"srt_action",/*idx*/"sqlite_autoindex_srt_action_1",/*stat*/"41 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"arena_defence_reward",/*idx*/NULL,/*stat*/"1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"banner",/*idx*/NULL,/*stat*/"88");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"stationary_mission_data",/*idx*/NULL,/*stat*/"828");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"dear_chara",/*idx*/"dear_chara_0_event_id",/*stat*/"18 3");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"dear_chara",/*idx*/"sqlite_autoindex_dear_chara_1",/*stat*/"18 3 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_enemy_data",/*idx*/NULL,/*stat*/"599");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unique_equipment_enhance_data",/*idx*/"sqlite_autoindex_unique_equipment_enhance_data_1",/*stat*/"159 159 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"kmk_navi_comment",/*idx*/NULL,/*stat*/"11");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unique_equipment_enhance_rate",/*idx*/NULL,/*stat*/"74");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_item",/*idx*/NULL,/*stat*/"34");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_motion_list",/*idx*/NULL,/*stat*/"108");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unique_equipment_rankup",/*idx*/"unique_equipment_rankup_0_equip_id",/*stat*/"592 8");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unique_equipment_rankup",/*idx*/"sqlite_autoindex_unique_equipment_rankup_1",/*stat*/"592 8 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_emblem_mission_reward",/*idx*/"hatsune_emblem_mission_reward_0_reward_id",/*stat*/"86 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_emblem_mission_reward",/*idx*/"hatsune_emblem_mission_reward_0_mission_reward_id",/*stat*/"86 2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_schedule",/*idx*/"hatsune_schedule_0_series_event_id",/*stat*/"34 34");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_character_personality",/*idx*/NULL,/*stat*/"109");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_promotion",/*idx*/"unit_promotion_0_unit_id",/*stat*/"2116 16");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"unit_promotion",/*idx*/"sqlite_autoindex_unit_promotion_1",/*stat*/"2116 16 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"item_data",/*idx*/NULL,/*stat*/"217");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_s_boss_fix_reward",/*idx*/NULL,/*stat*/"126");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"reward_collect_guide",/*idx*/NULL,/*stat*/"426");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"kaiser_add_times_data",/*idx*/NULL,/*stat*/"192");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"pct_reward",/*idx*/"pct_reward_0_pct_point_type",/*stat*/"1 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"sekai_boss_fix_reward",/*idx*/NULL,/*stat*/"5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"clan_battle_boss_fix_reward",/*idx*/NULL,/*stat*/"40");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"room_setup",/*idx*/NULL,/*stat*/"350");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"event_navi_comment",/*idx*/NULL,/*stat*/"21");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"cooperation_quest_data",/*idx*/NULL,/*stat*/"6");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"chara_e_ticket_data",/*idx*/"chara_e_ticket_data_0_jewel_store_id",/*stat*/"1 1");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"tower_cloister_quest_data",/*idx*/NULL,/*stat*/"5");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"hatsune_bg_change",/*idx*/NULL,/*stat*/"2");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"guild",/*idx*/NULL,/*stat*/"17");
INSERT INTO `sqlite_stat1` VALUES (/*tbl*/"mission_reward_data",/*idx*/"mission_reward_data_0_mission_reward_id",/*stat*/"346 2");
COMMIT;